New Update: Mathematical Equations in mainPanel for SIR and other models
ashokkrish/episim pull request #31
Opened 2024-05-12 02:58 UTC by kle6951

**_Features were implemented:_** 
**1** I finished adding the mathematical equations for the SIRS model in the main panel (ie: Write the necessary LaTeX generating function in R/model_LaTeX.R) addressed by Bryce's notes in #17. 
**2** I updated the section `Reproductive ratio` by using the curly bracket for the conditions as Ashok has mentioned before 

**_There are a few things needed to consider:_**
1. Please double-check the mathematical equation for the reproductive ratio of the SIRS 
2. In the SIRS model, based on the equations provided by Ashok, I left the population as `N` instead of `N^q` in other models. Please let me know which one is more preferable.
3. Please double-check the Greek symbol as `\nu` mentioned in my comments in the code

2024-05-12 03:59 UTC, ashokkrish commented
We have to have a separate meeting to derive and print the **basic reproduction number (_R_0)** for each model. I will assign a specific set of articles/book chapters that helps us with the derivation. This will involve inverting and multiplying matrices and then eventually calculating the largest eigenvalue. More details to follow.

2024-05-12 04:55 UTC, ashokkrish commented
I would like the ODEs rendered without this left border text

<img width="101" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/ad909c1b-c14c-45c2-bbfa-8d8488ddc1cf">

Let's left indent all the equations. For example, an SIR model without vital dynamics under the pseudo mass action formulation would look like this

<img width="139" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/8dc0f2a7-9bb3-4508-be4d-6091a3a6a92d">

Another example, an SEIRD model under the true mass action formulation would like this

<img width="179" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/10b39f08-7182-429c-b5b4-c81f83ae12f2">

2024-05-13 18:07 UTC, bryce-carson requested changes
- There are some requested changes needed to make the $\LaTeX{}$ readable.
- Please amend the commit and remove the Rproj file.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +           "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +           "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on R/model_LaTeX.R
> +      "q-Value $$\\begin{equation} x = \\begin{cases} 1 & \\text{, } frequency − dependent \\\\ 0 & \\text{, } density − dependent \\end{cases}\\end{equation} $$"
Please use raw strings when writing $\LaTeX{}$. Inside the raw string you will only have to write $\LaTeX{}$, and won't need to escape backslash characters which are used to call macros and commands.

2024-05-13 18:07 UTC, bryce-carson commented on episimFork.Rproj
Please ammend the commit and unstage this file.

2024-05-13 18:34 UTC, kle6951 commented
I have made the changes. Please let me know if anything needs to be fixed.

2024-05-13 19:23 UTC, bryce-carson commented on episimFork.Rproj
Don't worry about this anymore.

2024-05-13 19:24 UTC, bryce-carson commented
> I have made the changes. Please let me know if anything needs to be fixed.

I don't see any new commits to this branch. Where did you make the changes?

2024-05-13 19:26 UTC, kle6951 commented
> > I have made the changes. Please let me know if anything needs to be fixed.
> 
> I don't see any new commits to this branch. Where did you make the changes?

Are you able to see that I made changes by using the r"()" for the LaTex? I committed the changes already. If you don't see it, I will commit again

2024-05-13 19:32 UTC, bryce-carson commented
> > > I have made the changes. Please let me know if anything needs to be fixed.
> > 
> > 
> > I don't see any new commits to this branch. Where did you make the changes?
> 
> Are you able to see that I made changes by using the r"()" for the LaTex? I committed the changes already. If you don't see it, I will commit again

No, I don't see the changes here. You can look at the commits for this PR by selecting the Commits tab in the tab bar below the PR title. That only shows the first commit you made to this PR, and then a commit I made which resolves a merge conflict.

Make sure you check out this branch (`feat-LaTex`, note the casing) and then make the commit and push to the remote branch.

2024-05-13 19:41 UTC, kle6951 commented
I committed to the branch already. Please review it.

2024-05-13 19:41 UTC, bryce-carson commented
> I committed to the branch already. Please review it.

The commit to the branch is visible now. Thanks.

2024-05-13 19:42 UTC, merged